### ISSUE TITLE
Number of projects fetched

### ISSUE THREAD

**Issue by chechu** [ujiro99/RedmineTimeTracker#13]
Hi,
Firstly, good job :-)

Nowadays the number of projects fetched from the server is 50 (fix in mainCtrl.coffee:58). For administrators or organizations with a bigger number of projects, this fix number could be a limitation. What do you think about adding a new configurable parameter (as "Number of issues per Page.") for allowing to configure this number?

**Comment by ujiro99** [comment]
Today, it has been updated with your PR. please try it :-)
