### ISSUE TITLE
Manual tracking - hrs, days, wk in addition to mins

### ISSUE THREAD

**Issue by arturol76** [ujiro99/RedmineTimeTracker#15]
Manual configuration:
It would be great to have the chance to enter the time spent not only in minutes, but also in hours, days and weeks. Something like this:
8h --> 8 hours
2d --> 2 days
3w --> 3 weeks

What do you think?

**Comment by ujiro99** [comment]
It is a good idea to add non-minute units of input.
But, I want to consider about UI to enter. I want to make it more easy to understand.
Something like this demo:
http://recras.github.io/angular-jquery-timepicker/

**Comment by arturol76** [comment]
Nice.
Another way could be to add a "mins or hours" parameter in the settings. 
If the user select "hours", the UI control will treat the number written by user as hours.

This is a simple way but absolutely enough in my case: I will always use hours.

**Comment by ujiro99** [comment]
OK.
I will try it today!

**Comment by ujiro99** [comment]
I released cfcdbdf53d166731ac5abee67e7bf8d2790b30b4.
In option, you can set step to a hour.
Please try v0.7.11.
