### ISSUE TITLE
Can we please have functionality for ticket type:Billed/Non-Billed and ticket status changes.

### ISSUE THREAD

**Issue by dhaval-aspire** [ujiro99/RedmineTimeTracker#17]
It will be great if it has feature of ticket type "Billed/Non-Billed" and ticket status like::"open, in-progress, closed"

**Comment by ujiro99** [comment]
You can use "Custom Queries" on RTT's Issues > Search Options.
 
![query](https://cloud.githubusercontent.com/assets/677231/15268931/2fa917b6-1a2a-11e6-8a32-5e4fb81250dd.png)

If you want to know how to create Custom queries, Please refer [Custom queries](http://www.redmine.org/projects/redmine/wiki/RedmineIssueList#Custom-queries).
