### ISSUE TITLE
How I can call  onSubmitClick in my own handler? (I want to stop time tracker by event)

### ISSUE THREAD

**Issue by Voodoo773** [ujiro99/RedmineTimeTracker#20]
Greetings. We have some task. We want start/stop tracking time on a client. How we can сall function that will send data to the server and stop tracking time. We found function "onSubmitClick" in "Auto constructor", is it? How we can call this function in our handler function using native js, or coffeescript.

**Comment by ujiro99** [comment]
Native js means outside of angular.js?
I think it is difficult. So I tried to enables to start/stop tracking from  window scope.
This branch commit.
29fe79a36d078e3c01f8b0882b4c3bdc523e7b59

You can start/stop tracking using window.toggleTracking().
Does this commit solves your problem?
